package com.ledgerlens.backend.plaid;

import com.ledgerlens.backend.account.Account;
import com.ledgerlens.backend.account.AccountRepository;
import com.plaid.client.model.*;
import com.plaid.client.request.PlaidApi;
import java.io.IOException;
import java.util.List;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import retrofit2.Response;


// recall: @RestController defines a web controller class, and @RequestMapping sets the base URL for that class.
@RestController
@RequestMapping("/api/plaid")
public class PlaidController{

    // both dependencies injected by container...
    // 1. PlaidApi came from PlaidConfig's @Bean method
    // 2. AccountRepository was generated by Spring Data.
    private final PlaidApi plaid;
    private final AccountRepository accounts;

    public PlaidController(PlaidApi plaid, AccountRepository accounts){
        this.plaid = plaid;
        this.accounts = accounts;
    }

    // STEP 1: browser asks for link_token to open Plaid Link.
    // Short-lived -> safe to expose
    @PostMapping("/link-token")

}