package com.ledgerlens.backend.plaid;

import com.ledgerlens.backend.account.Account;
import com.ledgerlens.backend.account.AccountRepository;
import com.plaid.client.model.*;
import com.plaid.client.request.PlaidApi;
import java.io.IOException;
import java.util.List;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import retrofit2.Response;


// recall: @RestController defines a web controller class, and @RequestMapping sets the base URL for that class.
@RestController
@RequestMapping("/api/plaid")
public class PlaidController{
    // both dependencies injected by container...
    // 1. PlaidApi came from PlaidConfig's @Bean method
    // 2. AccountRepository was generated by Spring Data.
    private final PlaidApi plaid;
    private final AccountRepository accounts;
    // 3. PlaidSyncService is a @Service bean, injected the same way.
    private final PlaidSyncService syncService;

    public PlaidController(PlaidApi plaid, AccountRepository accounts, PlaidSyncService syncService){
        this.plaid = plaid;
        this.accounts = accounts;
        this.syncService = syncService;
    }

    // STEP 1: browser asks for a link_token to open Plaid Link.
    @PostMapping("/link-token")
    public ResponseEntity<?> createLinkToken() throws IOException{
        // stable id for this user
        // single-user project -> constant
        LinkTokenCreateRequest request = new LinkTokenCreateRequest()
            .user(new LinkTokenCreateRequestUser().clientUserId("ledger-lens-user-1"))
            .clientName("Ledger Lens")
            .products(List.of(Products.TRANSACTIONS))
            .countryCodes(List.of(CountryCode.US))
            .language("en");

        // Retrofit: build, then .execute() to actually make the HTTP call.
        // This is where I hit plaid's servers
        Response<LinkTokenCreateResponse> response =  plaid.linkTokenCreate(request).execute();
        if (!response.isSuccessful()) {
            // errorBody() carries Plaid's diagnostics — bad keys show up here,
            // NOT as an exception. Surfacing it saves hours of guessing.
            return ResponseEntity.status(502).body(
                    "Plaid error: " + response.errorBody().string()); // ResponseEntity<T> is a class in Spring Boot used to represent the complete HTTP response
        }
        
        return ResponseEntity.ok(java.util.Map.of("linkToken", response.body().getLinkToken()));

    }
    // DEV ONLY: sandbox lets us mint a public_token WITHOUT a browser, so the
    // whole flow is testable by curl before the frontend exists (Step 24).
    // ins_109508 = "First Platypus Bank", Plaid's standard sandbox institution.
    @PostMapping("/sandbox-public-token")
    public ResponseEntity<?> sandboxPublicToken() throws IOException {
        SandboxPublicTokenCreateRequest request = new SandboxPublicTokenCreateRequest()
                .institutionId("ins_109508")
                .initialProducts(List.of(Products.TRANSACTIONS));

        Response<SandboxPublicTokenCreateResponse> response =
                plaid.sandboxPublicTokenCreate(request).execute();
        if (!response.isSuccessful()) {
            return ResponseEntity.status(502).body("Plaid error: " + response.errorBody().string());
        }
        return ResponseEntity.ok(java.util.Map.of("publicToken", response.body().getPublicToken()));
    }

    // Step 2: public_token -> access_token
    // After the client launches the Plaid Link UI and logs in to their bank, they get a public_token
    // This public_token is sent to spring boot server, which exchanges it for a permenant access_token
    // access_token returned here is long-lived and must never appear in response body or log
    @PostMapping("/exchange")
    public ResponseEntity<?> exchange(@RequestBody ExchangeRequest body) throws IOException{
        Response<ItemPublicTokenExchangeResponse> exchanged = plaid.itemPublicTokenExchange(
                new ItemPublicTokenExchangeRequest().publicToken(body.publicToken())).execute();
        if (!exchanged.isSuccessful()) {
            return ResponseEntity.status(502).body("Plaid error: " + exchanged.errorBody().string());
        }

        String accessToken = exchanged.body().getAccessToken();

        // One access_token can cover several accounts (checking + savings at
        // the same bank), so ask which ones it unlocked and store a row each.
        Response<AccountsGetResponse> fetched = plaid.accountsGet(
                new AccountsGetRequest().accessToken(accessToken)).execute();
        if (!fetched.isSuccessful()) {
            return ResponseEntity.status(502).body("Plaid error: " + fetched.errorBody().string());
        }

        for (AccountBase plaidAccount : fetched.body().getAccounts()) {
            // IDEMPOTENCY, first appearance: re-linking the same bank must not
            // duplicate rows. Same principle drives transaction sync in Step 8.
            if (accounts.findByPlaidAccountId(plaidAccount.getAccountId()).isEmpty()) {
                accounts.save(new Account(
                        plaidAccount.getAccountId(),
                        accessToken,
                        plaidAccount.getName(),
                        String.valueOf(plaidAccount.getSubtype())));
            }
        }

        // Note what we return: a COUNT, not the token. The client learns that
        // linking worked and nothing more.
        return ResponseEntity.ok(java.util.Map.of(
                "linked", fetched.body().getAccounts().size()));
    }

    // STEP 3: pull transactions for every linked Item.
    // Synchronous for now — the caller waits for every page. Step 9 makes this
    // @Async and returns 202 immediately, because a first sync on a real bank
    // can take many seconds and no UI should block on it.
    @PostMapping("/sync")
    public ResponseEntity<?> sync() throws IOException {
        return ResponseEntity.ok(syncService.syncAll());
    }

    // A record as the request body: Jackson deserializes {"publicToken": "..."}
    // into this. Records make great DTOs in both directions.
    public record ExchangeRequest(String publicToken) {}
}