package com.ledgerlens.backend.advice;

import java.time.YearMonth;
import java.util.Map;
import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

// The advice endpoints my dashboard calls.
//
// Thin, like my other controllers — the assembly of ML output into advice inputs
// lives in AdviceAssembler, and the LLM policy lives in AdviceService.
@RestController
@RequestMapping("/api/advice")
public class AdviceController {

    private final AdviceAssembler assembler;
    private final AdviceService adviceService;

    public AdviceController(AdviceAssembler assembler, AdviceService adviceService) {
        this.assembler = assembler;
        this.adviceService = adviceService;
    }

    // GET /api/advice?accountId=2&month=2026-05
    //
    // Note this endpoint never fails because the LLM is unavailable. It returns
    // advice plus a `source` field ("claude", "claude-retry", or "rule-based")
    // so my dashboard can be honest about where the words came from rather than
    // implying every response was model-written.
    @GetMapping
    public AdviceAssembler.AdviceResponse advice(
            @RequestParam Long accountId,
            @RequestParam @DateTimeFormat(pattern = "yyyy-MM") YearMonth month) {
        return assembler.adviceFor(accountId, month);
    }

    // Lets my dashboard tell the user upfront whether advice will be
    // model-written or rule-based, instead of discovering it after a request.
    @GetMapping("/health")
    public Map<String, Object> health() {
        boolean available = adviceService.isLlmAvailable();
        return Map.of(
                "llmConfigured", available,
                "note", available
                        ? "Advice is generated by Claude with a rule-based fallback"
                        : "No API key configured — advice is rule-based");
    }
}
